import { OptionsType } from "@/types/OptionsType";

enum KaratOptionsEnum {
  K_01 = "1",
  K_02 = "2",
  K_03 = "3",
  K_04 = "4",
  K_05 = "5",
  K_06 = "6",
  K_07 = "7",
  K_08 = "8",
  K_09 = "9",
  K_10 = "10",
  K_11 = "11",
  K_12 = "12",
  K_13 = "13",
  K_14 = "14",
  K_15 = "15",
  K_16 = "16",
  K_17 = "17",
  K_18 = "18",
  K_19 = "19",
  K_20 = "20",
  K_21 = "21",
  K_22 = "22",
  K_23 = "23",
  K_24 = "24",
}

const KaratOptions: OptionsType<KaratOptionsEnum> = [
  { id: KaratOptionsEnum.K_24, title: KaratOptionsEnum.K_24 + " Karat" },
  { id: KaratOptionsEnum.K_23, title: KaratOptionsEnum.K_23 + " Karat" },
  { id: KaratOptionsEnum.K_22, title: KaratOptionsEnum.K_22 + " Karat" },
  { id: KaratOptionsEnum.K_21, title: KaratOptionsEnum.K_21 + " Karat" },
  { id: KaratOptionsEnum.K_20, title: KaratOptionsEnum.K_20 + " Karat" },
  { id: KaratOptionsEnum.K_19, title: KaratOptionsEnum.K_19 + " Karat" },
  { id: KaratOptionsEnum.K_18, title: KaratOptionsEnum.K_18 + " Karat" },
  { id: KaratOptionsEnum.K_17, title: KaratOptionsEnum.K_17 + " Karat" },
  { id: KaratOptionsEnum.K_16, title: KaratOptionsEnum.K_16 + " Karat" },
  { id: KaratOptionsEnum.K_15, title: KaratOptionsEnum.K_15 + " Karat" },
  { id: KaratOptionsEnum.K_14, title: KaratOptionsEnum.K_14 + " Karat" },
  { id: KaratOptionsEnum.K_13, title: KaratOptionsEnum.K_13 + " Karat" },
  { id: KaratOptionsEnum.K_12, title: KaratOptionsEnum.K_12 + " Karat" },
  { id: KaratOptionsEnum.K_11, title: KaratOptionsEnum.K_11 + " Karat" },
  { id: KaratOptionsEnum.K_10, title: KaratOptionsEnum.K_10 + " Karat" },
  { id: KaratOptionsEnum.K_09, title: KaratOptionsEnum.K_09 + " Karat" },
  { id: KaratOptionsEnum.K_08, title: KaratOptionsEnum.K_08 + " Karat" },
  { id: KaratOptionsEnum.K_07, title: KaratOptionsEnum.K_07 + " Karat" },
  { id: KaratOptionsEnum.K_06, title: KaratOptionsEnum.K_06 + " Karat" },
  { id: KaratOptionsEnum.K_05, title: KaratOptionsEnum.K_05 + " Karat" },
  { id: KaratOptionsEnum.K_04, title: KaratOptionsEnum.K_04 + " Karat" },
  { id: KaratOptionsEnum.K_03, title: KaratOptionsEnum.K_03 + " Karat" },
  { id: KaratOptionsEnum.K_02, title: KaratOptionsEnum.K_02 + " Karat" },
  { id: KaratOptionsEnum.K_01, title: KaratOptionsEnum.K_01 + " Karat" },
];

export { KaratOptions, KaratOptionsEnum };
